plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = mod_version
group = mod_group_id

def mavenUrl = System.getenv("MAVEN_URL")
def mavenUser = System.getenv("MAVEN_USERNAME")
def mavenPass = System.getenv("MAVEN_TOKEN")

def mc_version = "neoforge_${minecraft_version}"

repositories {
    mavenLocal()

    maven {
        url = "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content { includeGroup "maven.modrinth" }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers.add('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        c1 {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            gameDirectory = file('run/client_1')
            programArguments.addAll '--username', 'TestPlayer1'
        }

        c2 {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            gameDirectory = file('run/client_2')
            programArguments.addAll '--username', 'TestPlayer2'
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    jar {
        archiveBaseName.set(mod_id)
        archiveVersion.set(version)
        archiveFileName.set("${mod_id}-${mc_version}-${mod_version}.jar")
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }


dependencies {
    // Example mod dependency with JEI
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    //compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    //compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    //JEI
    implementation("mezz.jei:jei-${jei_mc_version}-neoforge:${jei_version}")

    implementation "curse.maven:jade-324717:7938398"

    runtimeOnly "curse.maven:bbl-core-1135181:${core_version}"
    compileOnly "curse.maven:bbl-core-1135181:${core_version}"

    runtimeOnly "curse.maven:bbl-routers-1334500:${router_version}"
    compileOnly "curse.maven:bbl-routers-1334500:${router_version}"


    //name-projectID:fileID
    localRuntime "curse.maven:contextmatters-1265417:7808075"
    localRuntime "curse.maven:pipematters-1494073:7808084"
    localRuntime "curse.maven:volumetrics-1240222:7806225"
    localRuntime "curse.maven:xycraft-653786:7808135"
    localRuntime "curse.maven:xycraft-world-653789:7808144"

    //localRuntime "curse.maven:ctm-267602:5587515"
    /*localRuntime "curse.maven:fusion-854949:7464745"
    localRuntime "curse.maven:smjnlib-454372:7522042"
    localRuntime "curse.maven:smjnconfiglib-438332:7376963"
    localRuntime "curse.maven:ctg-383129:7394727"

    localRuntime "curse.maven:resourcefullib-570073:7312675"*/
    //localRuntime "curse.maven:athena-841890:6669522"
    //localRuntime "curse.maven:chipped-456956:5813117"

    //localRuntime "curse.maven:rechiseled-558998:7589683"
    localRuntime "curse.maven:macaw_fences-453925:7809939"
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            artifactId = "${mod_id}-${mc_version}"
        }
    }

    repositories {
        if (mavenUrl && mavenUser && mavenPass) {
            maven {
                url = uri(mavenUrl)
                credentials {
                    username = mavenUser
                    password = mavenPass
                }
            }
        }
    }
}

tasks.named("publish") {
    doFirst {
        println ">>> Running publish task!"
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
